#!/bin/bash
cd ../src
g++ -std=c++11 -fopenmp -DDEGE_GS -DSLOWENUMALGO   -c -o mcce-metropolis.o mcce-metropolis.cpp #wlce.o new-wlce.cpp
g++ -fopenmp mcce-metropolis.o headers.o stringo.o parse.o xtalutil.o integer.o findsym.o calccorr.o clus_str.o getvalue.o wlcehelp.o linalg.o linsolve.o lstsqr.o  -lm -o mcce-metropolis-test
